#! /bin/sh
#
# jjnbparam
# Copyright (C) 2018 Mark Wells <mwellsa@gmail.com>
#
# Distributed under terms of the MIT license.
#

DIR="$(dirname "$(readlink -f "$0")")"

julia ${DIR}/jjnbparam.jl "$@"
jupyter nbconvert --to notebook \
    --execute \
    --allow-errors \
    --ExecutePreprocessor.timeout=-1 \
    "$2" --output "$2"
