#! /bin/sh
#
# jjnbparam
# Copyright (C) 2018 Mark Wells <mwellsa@gmail.com>
#
# Distributed under terms of the MIT license.
#

DIR="$(dirname "$(readlink -f "$0")")"
julia --color=yes ${DIR}/jjnbparam.jl $@
